name: API Tests with Allure

on:
  push:
    branches: ["**"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ["**"]
  workflow_dispatch:
  
env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Debug env
        run: env | grep DB_
    
      - name: Checkout tests repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run API container
        run: docker-compose -f docker-compose.ci.yml up -d

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install test dependencies
        run: pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Run API tests
        run: |
          pytest --alluredir=./allure-results

      - name: Install Allure
        if: always()
        uses: simple-elf/allure-report-action@v1.7

      - name: Upload Allure report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report


      - name: Check if report exists
        id: report_check
        run: |
          if [ -d "./allure-report" ] && [ "$(ls -A ./allure-report)" ]; then
            echo "report_exists=true" >> $GITHUB_OUTPUT
          else
            echo "report_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to GitHub Pages
        if: always() && steps.report_check.outputs.report_exists == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          keep_files: false

      - name: Stop containers
        if: always()
        run: docker-compose down
