name: API Tests with Allure

on:
  push:
    branches: ["**"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: ["**"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout tests repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Run API container
        run: docker-compose up -d

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Install test dependencies
        run: pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Run API tests
        run: |
          pytest tests/api_tests \
            -n auto \
            --count=20 \
            --alluredir=./allure-results

      - name: Install Allure CLI
        run: |
          sudo apt-get install -y default-jre
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          echo "/opt/allure/bin" >> $GITHUB_PATH

      - name: Check allure results
        id: check_results
        run: |
          if [ -d "./allure-results" ] && [ "$(ls -A ./allure-results)" ]; then
            echo "results_exist=true" >> $GITHUB_OUTPUT
          else
            echo "results_exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate Allure report
        if: always() && steps.check_results.outputs.results_exist == 'true'
        run: allure generate ./allure-results --clean -o ./allure-report

      - name: Upload Allure report
        if: always() && steps.check_results.outputs.results_exist == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        if: always() && steps.check_results.outputs.results_exist == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          keep_files: false

      - name: Stop containers
        if: always()
        run: docker-compose down
